# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrence_id', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=120, null=True)),
                ('otp', models.PositiveSmallIntegerField(default=0)),
                ('flag', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
