# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_type', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='payment_data',
            name='domain',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
