# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20160903_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_data',
            old_name='domain',
            new_name='domain_type',
        ),
    ]
