# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_data_last_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_data',
            old_name='last_transaction',
            new_name='last_transaction_id',
        ),
    ]
