# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20160904_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_data',
            name='last_transaction_id',
            field=models.IntegerField(default=0),
        ),
    ]
