# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160831_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='flag_exam_centre_2',
        ),
        migrations.AddField(
            model_name='user_data',
            name='exam_centre_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='exam_centre_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
