# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20160831_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='flag_exam_centre_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
