# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_data_flag_exam_centre_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
