# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_exam_center_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_center_data',
            name='exam_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
