# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20160907_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='flag_exam_group',
            new_name='flag_exam_group_1',
        ),
        migrations.AddField(
            model_name='user_data',
            name='exam_group_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='exam_group_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='flag_exam_group_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_data',
            name='image',
            field=models.FileField(default='/media/default.png', upload_to='user_images'),
        ),
    ]
