# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20160913_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='user_images'),
        ),
    ]
