# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160913_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='/media/user_images/'),
        ),
    ]
